save_folder: '../../../../results/CAE_Koopman/Cylinder/cylinder_model_weights'
seq_length: 12
num_epochs: 300
decay_step: 20
batch_size: 24
learning_rate: 0.001
decay_rate: 0.9
lamb: 1.0
patience: 50
# multi_step: 10