save_folder: '../../../../results/CAE_MI/Dam/entropy_visual2'
seq_length: 12
num_epochs: 100
decay_step: 20
batch_size: 128
learning_rate: 0.001
decay_rate: 0.9
lamb: 1.0
alpha: 1.0
beta: 0.0
mi_k: 3
mi_temperature: 0.07
patience: 100