save_folder: '../../../../results/CAE_Koopman/Cylinder/3loss_model'
seq_length: 16
num_epochs: 300
decay_step: 20
batch_size: 16 # 16
learning_rate: 0.001
decay_rate: 0.8
lamb: 0.5
lamb_latent: 0.1
lamb_multi: 1.0
multi_step: 5
patience: 50
