save_folder: '../../../../results/CAE_MI/Dam/model_weights_L512'
seq_length: 12
num_epochs: 500
decay_step: 20
batch_size: 12
learning_rate: 0.001
decay_rate: 0.9
lamb: 0.1
alpha: 2.0
beta: 0.01
mi_k: 3
mi_temperature: 0.07
patience: 50