save_folder: '../../../../results/CAE_Koopman/Cylinder/cylinder_model_weights_L512'
seq_length: 16
num_epochs: 300
decay_step: 20
batch_size: 16
learning_rate: 0.001
decay_rate: 0.8
lamb: 0.1
patience: 50