save_folder: '../../../../results/CAE_MI/ERA5/3loss_model'
seq_length: 10
num_epochs: 300
decay_step: 20
batch_size: 16
learning_rate: 0.001
decay_rate: 0.9
lamb: 0.5
lamb_ms: 1.0
alpha: 2.0
beta: 0.01
mi_k: 3
mi_temperature: 0.07
multi_step: 5
patience: 50