train_mode: 'jointly'  # 'jointly', 'separately', 'multiply'
jointly_save_folder: '../../../../results/CAE_Linear/KMG/jointly_model_weights'
cae_save_folder: '../../../../results/CAE_Linear/KMG/separately_cae_model_weights'
linear_save_folder: '../../../../results/CAE_Linear/KMG/separately_linear_model_weights'
seq_length: 10
S1_epochs: 300
S2_epochs: 100
S3_epochs: 100
decay_step: 20
weight_decay: 1e-4
batch_size: 128
learning_rate: 0.0001
decay_rate: 0.9
lamb: 1.0