train_mode: 'jointly'
jointly_save_folder: '../../../../results/WAE/Cylinder/4loss_model'
# cae_save_folder: '../../../../results/WAE/Cylinder/separately_cae_model_weights'
# linear_save_folder: '../../../../results/WAE/Cylinder/separately_linear_model_weights'
seq_length: 16
S1_epochs: 300
S2_epochs: 80
S3_epochs: 80
decay_step: 20
batch_size: 128
learning_rate: 0.001
decay_rate: 0.8
lamb: 0.5
lamb_latent: 0.1
lamb_multi: 1.0
multi_step: 5
