train_mode: 'jointly'
jointly_save_folder: '../../../../results/CAE_MLP/Cylinder/model_weights'
seq_length: 12
S1_epochs: 300
S2_epochs: 80
S3_epochs: 80
decay_step: 20
batch_size: 128
learning_rate: 0.001
decay_rate: 0.9
lamb: 1.0
lamb_linear: 1.0