save_folder: '../../../../results/CAE_Weaklinear/KMG/3loss_model'
seq_length: 12
num_epochs: 100
decay_step: 20
batch_size: 32
learning_rate: 0.001
decay_rate: 0.9
weight_decay: 1.0e-4
lamb: 0.6
lamb_ms: 0.8
lamb_latent: 0.5
multi_step: 3
patience: 50

load_model: False
ckpt_path: ''