Cylinder:
  data_path: "../../../../data/cylinder/cylinder_train_data.npy"
  out_dir: "../../../../results/CGKN/Cylinder"
  seq_length: 12
  dt: 0.001
  train_split: 1.0
  obs_ratio: 0.15
  obs_layout: "random"
  min_spacing: 4
  save_probe_coords: true
  use_channels: [0, 1]
  dim_z: 512
  hidden: 128
  device: "cuda"
  seed: 42
  bs: 64
  num_workers: 16
  s1_epochs: 100
  s1_short_steps: 6
  s1_lr: 0.0005
  s2_epochs: 50
  s2_short_steps: 6
  s2_long_steps: 12
  s2_cut_warmup: 5
  s2_lr: 0.001
  kalman_reg: 1.0e-6
  use_pretrained_stage1: False
  stage1_ckpt_prefix: "stage1"
  stage1_ckpt_dir: "../../../../results/CGKN/Cylinder"
  debug_stage2: false
  debug_batches: 1
  kalman_sigma_min_obs: 0.01
  kalman_sigma_max_obs: 1.0
  kalman_sigma_min_latent: 0.01
  kalman_sigma_max_latent: 1.0
  kalman_min_var: 1.0e-6
  kalman_max_var: 1.0
  kalman_cov_clip: 1.0
  kalman_gain_clip: 50.0
  kalman_gain_scale: 0.001
  kalman_innovation_clip: 1.0
  kalman_drift_clip: 0.1
  kalman_state_clip: 10.0
  kalman_use_diag_cov: true
  lam_ae: 1.0
  lam_forecast: 1.0
  lam_latent_forecast: 1.0
  lam_da: 1.0
ERA5:
  data_path: "../../../../data/ERA5/ERA5_data/train_seq_state.h5"
  min_path: "../../../../data/ERA5/ERA5_data/min_val.npy"
  max_path: "../../../../data/ERA5/ERA5_data/max_val.npy"
  out_dir: "../../../../results/CGKN/ERA5"
  seq_length: 10
  dt: 0.001
  train_split: 1.0
  obs_ratio: 0.15
  obs_layout: "random"
  min_spacing: 4
  save_probe_coords: true
  use_channels: [0, 1, 2, 3, 4]
  dim_z: 512
  hidden: 128
  device: "cuda"
  seed: 42
  bs: 64
  num_workers: 16
  s1_epochs: 100
  s1_short_steps: 6
  s1_lr: 0.001
  s2_epochs: 50
  s2_short_steps: 6
  s2_long_steps: 10
  s2_cut_warmup: 5
  s2_lr: 0.001
  kalman_reg: 1.0e-6
  use_pretrained_stage1: False
  stage1_ckpt_prefix: "stage1"
  stage1_ckpt_dir: "../../../../results/CGKN/ERA5"
  debug_stage2: false
  debug_batches: 1
  kalman_sigma_min_obs: 0.01
  kalman_sigma_max_obs: 1.0
  kalman_sigma_min_latent: 0.01
  kalman_sigma_max_latent: 1.0
  kalman_min_var: 1.0e-6
  kalman_max_var: 1.0
  kalman_cov_clip: 1.0
  kalman_gain_clip: 50.0
  kalman_gain_scale: 0.001
  kalman_innovation_clip: 1.0
  kalman_drift_clip: 0.1
  kalman_state_clip: 10.0
  kalman_use_diag_cov: true
  lam_ae: 1.0
  lam_forecast: 1.0
  lam_latent_forecast: 1.0
  lam_da: 1.0
ERA5_High:
  data_path: "../../../../data/ERA5_high/raw_data/weatherbench_train.h5"
  min_path: "../../../../data/ERA5_high/raw_data/era5high_240x121_min.npy"
  max_path: "../../../../data/ERA5_high/raw_data/era5high_240x121_max.npy"
  out_dir: "../../../../results/CGKN/ERA5_High"
  seq_length: 10
  dt: 0.001
  train_split: 1.0
  obs_ratio: 0.15
  obs_layout: "random"
  min_spacing: 4
  save_probe_coords: true
  use_channels: [0, 1, 2, 3, 4]
  dim_z: 512
  hidden: 128
  device: "cuda"
  seed: 42
  bs: 64
  num_workers: 16
  s1_epochs: 100
  s1_short_steps: 6
  s1_lr: 0.001
  s2_epochs: 50
  s2_short_steps: 6
  s2_long_steps: 10
  s2_cut_warmup: 5
  s2_lr: 0.001
  kalman_reg: 1.0e-6
  use_pretrained_stage1: False
  stage1_ckpt_prefix: "stage1"
  stage1_ckpt_dir: "../../../../results/CGKN/ERA5_High"
  debug_stage2: false
  debug_batches: 1
  kalman_sigma_min_obs: 0.01
  kalman_sigma_max_obs: 1.0
  kalman_sigma_min_latent: 0.01
  kalman_sigma_max_latent: 1.0
  kalman_min_var: 1.0e-6
  kalman_max_var: 1.0
  kalman_cov_clip: 1.0
  kalman_gain_clip: 50.0
  kalman_gain_scale: 0.001
  kalman_innovation_clip: 1.0
  kalman_drift_clip: 0.1
  kalman_state_clip: 10.0
  kalman_use_diag_cov: true
  lam_ae: 1.0
  lam_forecast: 1.0
  lam_latent_forecast: 1.0
  lam_da: 1.0
Kolmogorov:
  data_path: "../../../../data/kol/kolmogorov_train_data.npy"
  out_dir: "../../../../results/CGKN/KMG"
  seq_length: 10
  dt: 0.001
  train_split: 1.0
  obs_ratio: 0.15
  obs_layout: "random"
  min_spacing: 4
  save_probe_coords: true
  use_channels: [0]
  dim_z: 512
  hidden: 128
  device: "cuda"
  seed: 42
  bs: 64
  num_workers: 16
  s1_epochs: 100
  s1_short_steps: 6
  s1_lr: 0.0001
  s2_epochs: 50
  s2_short_steps: 6
  s2_long_steps: 10
  s2_cut_warmup: 5
  s2_lr: 0.0001
  kalman_reg: 1.0e-6
  use_pretrained_stage1: False
  stage1_ckpt_prefix: "stage1"
  stage1_ckpt_dir: "../../../../results/CGKN/KMG"
  debug_stage2: false
  debug_batches: 1
  kalman_sigma_min_obs: 0.01
  kalman_sigma_max_obs: 1.0
  kalman_sigma_min_latent: 0.01
  kalman_sigma_max_latent: 1.0
  kalman_min_var: 1.0e-6
  kalman_max_var: 1.0
  kalman_cov_clip: 1.0
  kalman_gain_clip: 50.0
  kalman_gain_scale: 0.001
  kalman_innovation_clip: 1.0
  kalman_drift_clip: 0.1
  kalman_state_clip: 10.0
  kalman_use_diag_cov: true
  lam_ae: 1.0
  lam_forecast: 1.0
  lam_latent_forecast: 1.0
  lam_da: 1.0
