# Model parameters
rank: 512
seq_length: 10

use_gpu: False

save_folder: "../../../../results/DMD/ERA5_High"
train_data_path: "../../../../data/ERA5_high/raw_data/weatherbench_train.h5"
min_path: "../../../../data/ERA5_high/raw_data/era5high_240x121_min.npy"
max_path: "../../../../data/ERA5_high/raw_data/era5high_240x121_max.npy"
