Cylinder:
  train_mode: jointly
  jointly_save_folder: '../../../../results/KAE/Cylinder/3loss_model'
  seq_length: 16
  S1_epochs: 300
  S2_epochs: 80
  S3_epochs: 80
  decay_step: 20
  batch_size: 128
  learning_rate: 0.001
  decay_rate: 0.8
  lamb: 0.5
  lamb_latent: 0.1
  lamb_multi: 1.0
  multi_step: 5
ERA5:
  save_folder: '../../../../results/KAE/ERA5/3loss_model'
  seq_length: 10
  num_epochs: 300
  decay_step: 20
  batch_size: 64
  learning_rate: 0.001
  decay_rate: 0.9
  lamb: 0.5
  lamb_ms: 1.0
  multi_step: 5
  patience: 50
ERA5_High:
  save_folder: '../../../../results/KAE/ERA5_High/3loss_model'
  seq_length: 10
  num_epochs: 100
  decay_step: 10
  batch_size: 64
  learning_rate: 0.001
  decay_rate: 0.9
  lamb: 0.5
  lamb_ms: 1.5
  multi_step: 3
  patience: 50
  train_data_path: '../../../../data/ERA5_high/raw_data/weatherbench_train.h5'
  val_data_path: '../../../../data/ERA5_high/raw_data/weatherbench_test.h5'
  min_path: '../../../../data/ERA5_high/raw_data/era5high_240x121_min.npy'
  max_path: '../../../../data/ERA5_high/raw_data/era5high_240x121_max.npy'
Kolmogorov:
  save_folder: '../../../../results/KAE/KMG/3loss_model'
  seq_length: 12
  num_epochs: 100
  decay_step: 20
  batch_size: 32
  learning_rate: 0.001
  decay_rate: 0.9
  weight_decay: 0.0001
  lamb: 0.6
  lamb_ms: 0.8
  multi_step: 3
  patience: 50
  load_model: false
  ckpt_path: ''
